
url: http://localhost:9999
twitter_username: askesian
github_username:  askesian

lsi: false
highlighter: true
markdown: kramdown
permalink: '/:title'

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    use_coderay: false

    coderay:
        coderay_wrap: div
        coderay_line_numbers: inline
        coderay_line_numbers_start: 1
        coderay_tab_width: 4
        coderay_bold_every: 10
        coderay_css: style

source: ./app
destination: ./build