# Permalinks
permalink:            pretty
relative_permalinks:  true

# Basic Properties
title:                askesian
tagline:              Supping life's nitrous oxide
description:          Crabwalking through the mind of a learner
url:                  http://localhost:9999
baseurl:              ''

# Contact
author:
  name:               Chris Wigley
  url:                https://twitter.com/askesian
  email:              cwigley@gmail.com
twitter_username:     askesian
github_username:      askesian

# Jekyll Stuff
lsi:                  false
highlighter:          pygments
markdown:             redcarpet

# Source Stuff
source:               ./app
destination:          ./build
future:               true
show_drafts:          true

# Custom
version:              1.0.0
github:
  repo:               https://github.com/askesian